version: '3'
# requires envs
## DIR_DOWNLOADS
## DIR_TV
## DIR_MOVIES
## BASE_URL
services:

  s-nginx-proxy:
    container_name: s-nginx-proxy
    image: jwilder/nginx-proxy:alpine
    #    network_mode: host
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-proxy

  s-home:
    image: serenity-home
    container_name: s-home
    depends_on:
      - s-nginx-proxy
    ports:
      - 8001:80
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=home.${BASE_URL}
      - VIRTUAL_PORT=80
    networks:
      - nginx-proxy
  
  s-unifi:
    container_name: s-unifi
    image: linuxserver/unifi:latest
    depends_on:
      - s-nginx-proxy
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=unifi.${BASE_URL}
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=8443
      - DESCRIPTION=Network
      - ICON_URL=https://miro-icmfxmvdkqz7ku.stackpathdns.com/wp-content/uploads/UniFi-App.png
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    volumes:
      - ./s-unifi/data/config:/config
    networks:
      - nginx-proxy

      #s-letsencrypt:
      #container_name: s-letsencrypt
      #image: jrcs/letsencrypt-nginx-proxy-companion
      # volumes:
      #- ${DIR_CERTS}:/etc/nginx/certs:rw
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      # volumes_from:
#    - s-nginx-proxy


  s-sonarr:
    image: linuxserver/sonarr:latest
    container_name: s-sonarr
    depends_on:
      - s-nginx-proxy
    ports:
      - 8989:8989
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=sonarr.${BASE_URL}
      - NETWORK_ACCESS=internal
      - DESCRIPTION=TV
      - ICON_URL=https://cloud.githubusercontent.com/assets/22151176/18439012/f061c0e2-7903-11e6-826a-bd36d6288fcb.png
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./s-sonarr/data/config/:/config
      - ${DIR_TV}:/tv
      - ${DIR_DOWNLOADS}:/downloads
    networks:
      - nginx-proxy

  s-radarr:
    image: linuxserver/radarr:latest
    container_name: s-radarr
    depends_on:
      - s-nginx-proxy
    ports:
      - 7878:7878
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=radarr.${BASE_URL}
      - NETWORK_ACCESS=internal
      - DESCRIPTION=Movies
      - ICON_URL=https://i.imgur.com/WfcxC8g.png
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./s-radarr/data/config/:/config
      - ${DIR_MOVIES}:/movies
      - ${DIR_DOWNLOADS}:/downloads
    networks:
      - nginx-proxy

  s-plex:
    container_name: s-plex
    image: timhaak/plex:latest
    network_mode: host
    depends_on:
      - s-nginx-proxy
    environment: 
      - VERSION=latest
      - PUID=1000 
      - PGID=1000
    ports:
      - 32400:32400 #(for access to the Plex Media Server) [required]
      - 32400:32400/udp
      - 32410:32410/udp #(for current GDM network discovery)
      - 32412:32412/udp 
      - 32413:32413/udp 
      - 32414:32414/udp
      - 32469:32469 #(for access to the Plex DLNA Server)
      - 32469:32469/udp
      - 5353:5353 # (for older Bonjour/Avahi network discovery)
      - 1900:1900/udp #(for access to the Plex DLNA Server)
    volumes:
      - ./s-plex/config/:/config
      - ./s-plex/transcode/:/transcode
      - ${DIR_MOVIES}:/data/movies
      - ${DIR_TV}:/data/tvshows
    expose:
      - 32400
        #networks:i
    #    - nginx-proxy

  s-nzbget:
    image: linuxserver/nzbget
    container_name: s-nzbget
    depends_on:
      - s-nginx-proxy
    ports:
      - 5789:6789
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=nzbget.${BASE_URL}
      - NETWORK_ACCESS=internal
      - DESCRIPTION=Downloader
      - ICON_URL=https://avatars2.githubusercontent.com/u/3368377?s=280&v=4
    volumes:
      - ./s-nzbget/data/config/:/config
      - ${DIR_DOWNLOADS}:/downloads
    networks:
      - nginx-proxy
  
  s-cnc:
    image: serenity-proxy-cnc
    container_name: s-cnc
    depends_on:
      - s-nginx-proxy
    environment:
      - VIRTUAL_HOST=cnc.${BASE_URL}
      - VIRTUAL_PORT=80
      - ICON_URL=https://www.clipartmax.com/png/middle/183-1838113_new-article-on-open-source-and-free-cnc-toolchain-cnc-icon.png
    networks:
      - nginx-proxy
  
  s-cnc-webcam:
    image: serenity-proxy-cnc-webcam
    container_name: s-cnc-webcam
    depends_on:
      - s-nginx-proxy
    environment:
      - VIRTUAL_HOST=webcam.cnc.${BASE_URL}
      - VIRTUAL_PORT=80
      - ICON_URL=https://www.clipartmax.com/png/middle/29-290333_raspberry-pi-camera-security-motion-eye-os-logo.png
    networks:
      - nginx-proxy

  s-pihole:
    image: pihole/pihole:latest
    container_name: s-pihole
    depends_on:
      - s-nginx-proxy
    ports:
      - 53:53
      - 67:67/udp
      - 446:443
    environment:
      - VIRTUAL_HOST=pihole.${BASE_URL}
      - VIRTUAL_PORT=80
      - ICON_URL=https://i2.wp.com/pi-hole.net/wp-content/uploads/2016/12/Vortex-R.png?zoom=2&w=3840&ssl=1
    volumes:
      - ./s-pihole/data/config/:/etc/pihole/
      - ./s-pihole/data/dnsmasq.d/:/etc/dnsmask.d/
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
