version: '3'
# requires envs
## DIR_DOWNLOADS
## DIR_TV
## DIR_MOVIES
## BASE_URL

services:


        
  s-nginx-proxy:
    container_name: s-nginx-proxy
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - s-home
      - s-sonarr
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
      #s-letsencrypt:
      #container_name: s-letsencrypt
      #image: jrcs/letsencrypt-nginx-proxy-companion
      # volumes:
      #- ${DIR_CERTS}:/etc/nginx/certs:rw
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      # volumes_from:
#    - s-nginx-proxy


  s-home:
    image: serenity-home
    container_name: s-home
    ports:
      - 8001:80
      - 444:443
    environment:
      - VIRTUAL_HOST=home.${BASE_URL}
      - DESCRIPTION=""
      - ICON_URL=http://www.stickpng.com/assets/images/588a6758d06f6719692a2d22.png


  s-sonarr:
    image: linuxserver/sonarr:latest
    container_name: s-sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=sonarr.${BASE_URL}
      - NETWORK_ACCESS=internal
      - DESCRIPTION=TV
      - ICON_URL=https://cloud.githubusercontent.com/assets/22151176/18439012/f061c0e2-7903-11e6-826a-bd36d6288fcb.png
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./s-sonarr/data/config/:/config
      - ${DIR_TV}:/tv
      - ${DIR_DOWNLOADS}/complete:/downloads


  s-radarr:
    image: linuxserver/radarr:latest
    container_name: s-radarr
    ports:
      - 7878:7878
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=radarr.${BASE_URL}
      - NETWORK_ACCESS=internal
      - DESCRIPTION=Movies
      - ICON_URL=https://i.imgur.com/WfcxC8g.png
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./s-radarr/data/config/:/config
      - ${DIR_MOVIES}:/movies
      - ${DIR_DOWNLOADS}/complete:/downloads


  s-emby:
    image: nvllsvm/emby-unlocked
    container_name: s-emby
    ports:
      - 8096:8096
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=emby.${BASE_URL}
      - NETWORK_ACCESS=internal
      - DESCRIPTION="Media Player"
      - ICON_URL=https://images-na.ssl-images-amazon.com/images/I/51WJTxymC6L.png
    volumes:
      - ./s-emby/data/config/:/config
      - ${DIR_TV}:/media/tv
      - ${DIR_MOVIES}:/media/movies


  s-nzbget:
    image: linuxserver/nzbget
    container_name: s-nzbget
    ports:
      - 6789:6789
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=nzbget.${BASE_URL}
      - NETWORK_ACCESS=internal
      - DDESCRIPTION=Downloader
      - ICON_URL=https://avatars2.githubusercontent.com/u/3368377?s=280&v=4
    volumes:
      - ./s-nzbget/data/config/:/config
      - ${DIR_DOWNLOADS}:/downloads
