# requires envs
## DIR_DOWNLOADS
## DIR_TV
## DIR_MOVIES






docker pull nvllsvm/emby-unlocked
 nzbget:
        image: linuxserver/nzbget
        container_name: nzbget
        volumes:
            - /path/to/nzbget/config:/config
            - /path/to/nzbget/downloads:/downloads
        restart: always
        environment:
            - TZ=America/New_York
        ports:
            - 6789:6789
            
                radarr:
        image: linuxserver/radarr
        container_name: radarr
        depends_on:
            - nzbget
        volumes:
            - /path/to/radarr/config:/config
            - /path/to/nzbget/downloads:/downloads
            - /path/to/plex/Movies:/movies
        environment:
            - TZ=America/New_York
        ports:
            - 7878:7878
            
            
            
# nginx-proxy:
#   container_name: nginx-proxy
#   image: alexanderkrause/rpi-nginx-proxy
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - /home/pi/nginx/certs:/etc/nginx/certs
  #     - /etc/nginx/vhost.d
  #     - /usr/share/nginx/html
  #   labels:
  #     - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  # letsencrypt:
  #   container_name: letsencrypt
  #   image: alexanderkrause/rpi-letsencrypt-nginx-proxy-companion
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /home/pi/nginx/certs:/etc/nginx/certs
  #   volumes_from:
  #     - nginx-proxy
  #   depends_on: 
  #     - nginx-proxy
            
            
            
            
            
            
            
serenity-home:
  image: serenity-home
  container_name: serenity-home
  links:
    - serenity-transmission:transmission
    - serenity-sonarr:sonarr
    - serenity-jackett:jackett
  ports:
    - 80:80
  environment:
    - SERENITY_NAME=Home
    - SERENITY_PORT=80
    - SERENITY_ICON_URL=http://www.stickpng.com/assets/thumbs/588a668cd06f6719692a2d1b.png

serenity-sonarr:
  image: linuxserver/sonarr
  container_name: serenity-sonarr
  ports:
    - 8989:8989
  environment:
    - PUID=1000 
    - PGID=1000
    - SERENITY_NAME=Sonarr
    - SERENITY_PORT=8989
    - SERENITY_ICON_URL=https://cloud.githubusercontent.com/assets/22151176/18439012/f061c0e2-7903-11e6-826a-bd36d6288fcb.png
  volumes:
    # In order to the container uses the same date which is in the host, it is necessary to share /etc/localtime file
    - /etc/localtime:/etc/localtime:ro
    - /dev/rtc:/dev/rtc:ro
    - ./s-sonarr/data/config/:/config
    - ${DIR_TV}:/tv
    - ${DIR_DOWNLOADS}/complete:/downloads

    
serenity-jackett:
    image: linuxserver/jackett
    container_name: serenity-jackett
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Pacific/Vancouver
      - SERENITY_NAME=Jackett
      - SERENITY_PORT=9117
      - SERENITY_ICON_URL=https://user-images.githubusercontent.com/27040483/28728094-99f3e3f6-73c7-11e7-8f8d-28912dc6ac0d.png
    volumes:
      - ./s-jackett/data/config:/config
      - ${DIR_DOWNLOADS}:/downloads
    ports:
      - 9117:9117
