version: '3'
# requires envs
## DIR_DOWNLOADS
## DIR_TV
## DIR_MOVIES
## BASE_URL

services:
  s-nginx-proxy:
    container_name: s-nginx-proxy
    image: jwilder/nginx-proxy:latest
    ports:
      - 80:80
      - 443:443
    depends_on:
      - s-home
      - s-sonarr
      - s-jackett
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  
      #s-letsencrypt:
      #container_name: s-letsencrypt
      #image: jrcs/letsencrypt-nginx-proxy-companion
      # volumes:
      #- ${DIR_CERTS}:/etc/nginx/certs:rw
      # - /var/run/docker.sock:/var/run/docker.sock:ro
      # volumes_from:
#    - s-nginx-proxy


  s-home:
    image: serenity-home
    container_name: serenity-home
    ports:
      - 8001:80
    environment:
      - VIRTUAL_HOST=home.${BASE_URL},localhost/home


  s-sonarr:
    image: linuxserver/sonarr:latest
    container_name: s-sonarr
    ports:
      - 8989:8989
    environment:
      - PUID=1000 
      - PGID=1000
      - VIRTUAL_HOST=sonarr.${BASE_URL},localhost/sonarr
      - SERENITY_NAME=Sonarr
      - SERENITY_PORT=8989
      - SERENITY_ICON_URL=https://cloud.githubusercontent.com/assets/22151176/18439012/f061c0e2-7903-11e6-826a-bd36d6288fcb.png
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev/rtc:/dev/rtc:ro
      - ./s-sonarr/data/config/:/config
      - ${DIR_TV}:/tv
      - ${DIR_DOWNLOADS}/complete:/downloads

    
  s-jackett:
    image: linuxserver/jackett:latest
    container_name: s-jackett
    ports:
      - 9117:9117
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Pacific/Vancouver
      - VIRTUAL_HOST=jackett.${BASE_URL},localhost/jackett
      - SERENITY_NAME=Jackett
      - SERENITY_PORT=9117
      - SERENITY_ICON_URL=https://user-images.githubusercontent.com/27040483/28728094-99f3e3f6-73c7-11e7-8f8d-28912dc6ac0d.png
    volumes:
      - ./s-jackett/data/config:/config
      - ${DIR_DOWNLOADS}:/downloads


