

serenity-sonarr:
  image: linuxserver/sonarr
  container_name: serenity-sonarr
  ports:
    - 8989:8989
  environment:
    - PUID=root 
    - PGID=root
    - SERENITY_NAME=Sonarr
    - SERENITY_PORT=8989
    - SERENITY_ICON_URL=https://cloud.githubusercontent.com/assets/22151176/18439012/f061c0e2-7903-11e6-826a-bd36d6288fcb.png
  volumes:
    # In order to the container uses the same date which is in the host, it is necessary to share /etc/localtime file
    - /etc/localtime:/etc/localtime:ro
    - /dev/rtc:/dev/rtc:ro
    - ./config:/config:rw
    - ./tvshows:/tv:rw

serenity-transmission:
  image: dperson/transmission
  container_name: serenity-transmission
  restart: always
  environment:
    - SERENITY_NAME=Transmission
    - SERENITY_PORT=9091
    - SERENITY_ICON_URL=https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Transmission_Icon.svg/480px-Transmission_Icon.svg.png
  env_file:
    - ./serenity=transmissioni/.env # for TRUSEr and TRPASSWD
  ports:
    - 9091:9091
  volumes:
    # In order to the container uses the same date which is in the host, it is necessary to share /etc/localtime file
    - /etc/localtime:/etc/localtime:ro
    - ./tvshows:/var/lib/transmission-daemon/downloads:rw
    
serenity-jackett:
    image: linuxserver/jackett
    container_name: serenity-jackett
    restart: always
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Pacific/Vancouver
      - SERENITY_NAME=Jackett
      - SERENITY_PORT=9117
      - SERENITY_ICON_URL=https://user-images.githubusercontent.com/27040483/28728094-99f3e3f6-73c7-11e7-8f8d-28912dc6ac0d.png
    volumes:
      - ${MOUNT_POINT}/jackett/config:/config
      - ${MOUNT_POINT}/jackett/downloads:/downloads
    ports:
      - "9117:9117"
